add ci cd for backend
nguyenquyhy/Hy-Academy pull request #31
Opened 2022-01-06 12:57 UTC by nguyenminhnhat138

2022-01-07 14:40 UTC, nguyenquyhy requested changes

2022-01-07 14:40 UTC, nguyenquyhy commented on Api/HyAcademy.GraphQL.Tools/HyAcademy.GraphQL.Tools.csproj
> +   <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" Exists('$(TargetDir)HyAcademy.GraphQL.Tools.exe') ">
```suggestion
  <!-- Windows -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" Exists('$(TargetDir)HyAcademy.GraphQL.Tools.exe') ">
```

2022-01-07 14:40 UTC, nguyenquyhy commented on Dockerfile
> +RUN dotnet build Api/HyAcademy.GraphQL.Tools/HyAcademy.GraphQL.Tools.csproj -c Debug
```suggestion
```

Có thể là ko cần nữa ah

2022-01-07 14:40 UTC, nguyenquyhy commented on Dockerfile
> +COPY React/schema.graphql react/
```suggestion
```
Cái này ko cần cho restore. Với khi build nó cũng regen.

2022-01-07 14:40 UTC, nguyenquyhy commented on Dockerfile
> +HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --silent --fail http://localhost/health || exit 1
Ủa cái API đã có health endpoint chưa?

2022-01-07 16:18 UTC, nguyenminhnhat138 commented on Dockerfile
> +HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --silent --fail http://localhost/health || exit 1
Dạ chưa, e refer bên moc pos, mà quên xóa ớ :D

2022-01-07 18:08 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-backend.yml
> +    - name: Check out the repo
Hình như step này cũng ko cần luôn, cái docker build nó tự handle

2022-01-08 02:57 UTC, nguyenminhnhat138 commented on .github/workflows/main-ci-cd-backend.yml
> +    - name: Check out the repo
dạ cái này vẫn cần, e có thử bỏ đi thì nó bị lỗi, e cũng có xem qua cái hướng dẫn của github, nó vẫn cần checkout á a
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
![image](https://user-images.githubusercontent.com/49674364/148629120-ae74a2d6-5605-48a0-bf0f-b6ee37562bd3.png)

2022-01-08 16:54 UTC, nguyenquyhy requested changes

2022-01-08 16:54 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-backend.yml
> +            environmentName="${{ secrets.REACT_STORAGE_ACCOUNT_NAME }}-container-app" \
```suggestion
            environmentName="${{ secrets.CONTAINER_APP_NAME }}" \
```

2022-01-09 16:10 UTC, nguyenquyhy requested changes

2022-01-09 16:10 UTC, nguyenquyhy commented on .azure/backend.bicep
> +resource containerApp 'Microsoft.Web/containerapps@2021-03-01' = {
Chắc sẽ cần cái output cho cái Application URL

2022-01-10 03:59 UTC, nguyenquyhy approved these changes

2022-01-10 04:02 UTC, merged