Create ci cd workflow for react app
nguyenquyhy/Hy-Academy pull request #7
Opened 2021-12-16 15:48 UTC by nguyenminhnhat138

resolve #1

2021-12-20 04:45 UTC, nguyenquyhy requested changes

2021-12-20 04:45 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +          creds: ${{ secrets.AZURE_CREDENTIALS }}
Anh có tạo cái environment Production, có cái environment secret là `DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIAL`

2021-12-20 04:45 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +            az storage blob upload-batch --account-name '{{ secrets.STORAGE_ACCOUNT_NAME }}' --auth-mode key -s './build' -d '$web'
Cũng trong environment Production, anh đã add `REACT_STORAGE_ACCOUNT_NAME`

2021-12-20 04:51 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +      - name: Upload to Storage Account
Xài bicep để tạo resource luôn dc ko, maybe thêm 1 job trước cái deploy.

2021-12-20 08:16 UTC, nguyenminhnhat138 commented on .github/workflows/main-ci-cd-frontend.yml
> +      - name: Upload to Storage Account
ok a

2021-12-21 11:47 UTC, nguyenquyhy requested changes

2021-12-21 11:47 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +          creds: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIAL }}
Change lần nữa thành DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIALS thử. Anh vừa tạo lại, thấy có vẻ work. Nhưng mà best thì change để nó auth bằng OIDC.

2021-12-23 20:50 UTC, nguyenquyhy requested changes

2021-12-23 20:50 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +  create-resource:
```suggestion
          path: ./React/build
          
  create-resource:
```

2021-12-23 20:50 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +      - name: azure login
```suggestion
      - name: Azure login
```

2021-12-23 20:50 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +      - name: create storage account by bicep
```suggestion
      - name: Create Azure resources
```

2021-12-23 20:50 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +      - name: azure logout
```suggestion
      - name: Azure logout
```

2021-12-23 20:50 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +      - name: azure login
```suggestion
      - name: Azure login
```

2021-12-23 20:50 UTC, nguyenquyhy commented on .azure/frontend.bicep
> +@maxLength(24)
Hình như cái annotation này là cho `storageAccountName` chứ ko phải `location`.

2021-12-23 20:50 UTC, nguyenquyhy commented on .azure/frontend.bicep
> +resource storageAccountEndpoint 'Microsoft.Cdn/profiles/endpoints@2020-09-01' = {
```suggestion
resource storageAccountCdnEndpoint 'Microsoft.Cdn/profiles/endpoints@2020-09-01' = {
```

2021-12-23 20:50 UTC, nguyenquyhy commented on .azure/frontend.bicep
> +}
Add cái endpoint hostname làm output nha

2021-12-23 20:50 UTC, nguyenquyhy commented on .azure/frontend.bicep
> +          name: 'SpaStaticFile'
Có thể consider chuyển cái này thành global rule (ko có condition). Cái rule trên nó sẽ overwrite cái global rule khi condition match.

2021-12-25 06:59 UTC, nguyenquyhy commented on .azure/frontend.bicep
> +    originHostHeader: replace(replace(storageAccountResource.properties.primaryEndpoints.blob, 'https://', ''), '/', '')
Thử function chưa?

2021-12-25 11:30 UTC, nguyenquyhy requested changes

2021-12-25 11:30 UTC, nguyenquyhy commented on .github/workflows/main-ci-cd-frontend.yml
> +      branches: [ main ]
```suggestion
```

2021-12-25 12:45 UTC, nguyenminhnhat138 commented on .azure/frontend.bicep
> +    originHostHeader: replace(replace(storageAccountResource.properties.primaryEndpoints.blob, 'https://', ''), '/', '')
dạ bicep chưa support function : https://github.com/Azure/bicep/issues/447

2021-12-25 12:51 UTC, nguyenquyhy approved these changes

2021-12-25 13:28 UTC, merged