[Lesson #81] add lesson for api
nguyenquyhy/Hy-Academy pull request #82
Opened 2022-02-10 16:13 UTC by nguyenminhnhat138

2022-02-10 16:50 UTC, nguyenquyhy requested changes
Nói chung anh nghĩ là ko cần change gì ở GraphQL cả. Trên UI hiện h có thể query lesson từ course. Chừng nào UI làm trang riêng cho lesson thì sẽ design cái query để lấy 1 lesson sau. Chủ yếu là mình ko nên tạo ra query mới quá sớm.

2022-02-10 16:50 UTC, nguyenquyhy commented on React/schema.graphql
> +  lesson(id: UUID!): Lesson
```suggestion
```
Cái root query này thì có thể là sẽ cần nếu mình làm 1 trang để coi lesson và trang đó chỉ theo lesson ID (trong URL) nên muốn giữ cái này cũng dc. Nhưng mà nên nhớ là khi làm GraphQL thì hạn chế add khi chưa cần dùng, do GraphQL rất dễ add nhưng rất khó change/remove (do 1 root query có thể dc dùng trong rất nhiều scenario khác nhau).

2022-02-10 16:50 UTC, nguyenquyhy commented on Api/HyAcademy.GraphQL/Query.cs
> +    public Task<IQueryable<Lesson>> GetLessons([Service] IGetLessonsQuery query) => query.Execute();
```suggestion
```
Anh nghĩ là sẽ ko cần query này.

Khi add GraphQL query thì em phải nghĩ về chuyện UI sẽ query như thế nào. Cho lessons thì UI sẽ ko query 1 list of lesson như vầy bao giờ do là lesson nó nằm trong course. Khi đó có nghĩa là khi lấy 1 list lesson thì sẽ luôn lấy theo course.

Nếu nghĩ theo hướng đó thì sẽ thấy là cái `lessons` này nó cần courseId. Nhưng nếu change thành `lesson(courseId: UUID!): [Lesson!]!` thì cũng ko đúng lắm. Cách đúng nhất trong GraphQL là để người ta query trực tiếp từ course, nghĩa là cái root query này là ko cần thiết.
```
query GetLessons {
  course(id: ...) {
    id
    lessons {
      id
      ...
    }
  }
}
```

2022-02-10 16:50 UTC, nguyenquyhy commented on Api/HyAcademy.GraphQL/Query.cs
> +    public Task<Lesson?> GetLesson([Service] IGetLessonQuery query, Guid id) => query.Execute(id);
```suggestion
```

Cái root query này thì có thể là sẽ cần nếu mình làm 1 trang để coi lesson và trang đó chỉ theo lesson ID (trong URL) nên muốn giữ cái này cũng dc. Nhưng mà nên nhớ là khi làm GraphQL thì hạn chế add khi chưa cần dùng, do GraphQL rất dễ add nhưng rất khó change/remove (do 1 root query có thể dc dùng trong rất nhiều scenario khác nhau).

2022-02-14 15:30 UTC, nguyenminhnhat138 commented on Api/HyAcademy.GraphQL/Query.cs
> +    public Task<IQueryable<Lesson>> GetLessons([Service] IGetLessonsQuery query, Guid id) => query.Execute(id);
dạ cái này e để nhầm, chỗ này ID là course ID, ko phải id của lesson, e đã split ra new branch cho phần này

2022-02-14 15:30 UTC, nguyenminhnhat138 commented on Api/HyAcademy.Data/Fakes/FakeData.cs
> +    public static List<Lesson> Lessons {get;} = new List<Lesson>{
e sẽ fix bên branch graqhql cho phần này

2022-02-14 16:29 UTC, nguyenquyhy commented on Api/HyAcademy.Data.EF/AppDbContext.cs
> +        modelBuilder.Entity<Lesson>().ToTable(nameof(Lesson));
Cái này ko cần, khi nào add DbSet thì mới cần.

2022-02-16 14:30 UTC, nguyenquyhy approved these changes

2022-02-20 04:50 UTC, nguyenquyhy requested changes
Migration có vẻ ko apply dc

2022-05-31 13:14 UTC, closed without merging